# Generated by Django 5.2.5 on 2025-08-18 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2023-01-01T12:00:00Z'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='profile-pictures/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tel',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='working_hours',
            field=models.CharField(default='9-17', max_length=255),
            preserve_default=False,
        ),
    ]
