# Generated by Django 5.2.5 on 2025-08-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth_app', '0002_customuser_created_at_customuser_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default='2023-09-15T09:00:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='description',
            field=models.TextField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='file',
            field=models.FileField(blank=True, default='', upload_to='profile-pictures/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tel',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='working_hours',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
