# Generated by Django 5.2.5 on 2025-08-29 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='updatede_at',
            new_name='updated_at',
        ),
    ]
