# Generated by Django 5.2.5 on 2025-08-29 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0007_alter_offer_min_price_alter_offerdetail_price'),
        ('orders_app', '0002_rename_updatede_at_order_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='offer_detail_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='offer_id', to='offers_app.offer'),
            preserve_default=False,
        ),
    ]
