# Generated by Django 5.2.5 on 2025-08-29 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0004_alter_order_delivery_time_in_days_alter_order_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='offer_detail_id',
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_time_in_days',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
