# Generated by Django 5.2.5 on 2025-08-29 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0005_remove_order_offer_detail_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='in_progress', max_length=255),
        ),
    ]
