# Generated by Django 5.2.5 on 2025-08-22 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0002_offer_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerdetail',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='offers_app.offer'),
        ),
    ]
