# Generated by Django 5.2.5 on 2025-08-25 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0006_alter_offerdetail_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='min_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='offerdetail',
            name='price',
            field=models.FloatField(),
        ),
    ]
