# Generated by Django 5.2.5 on 2025-09-04 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0007_alter_offer_min_price_alter_offerdetail_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerdetail',
            name='revisions',
            field=models.PositiveIntegerField(),
        ),
    ]
